version: "3.8"

services:
  project:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
