name: CI/CD
run-name: ${{github.actor}} CI/CD Pipeline on ${{github.ref_name}}
on:
  push:
    branches-ignore:
      - " ga-ignore-"

jobs:
  size:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check the size of the repository
        run: |
          SIZE=$(du -skh --exclude=.git | cut -f1)
          echo "The size of the repository is $SIZE"
          if [ $SIZE -gt 30000 ]; then
            echo "Size of the repository is too big"
            exit 1
          fi

  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        run: |
          sudo apt update && sudo apt install -y openjdk-23-jdk maven
          java -version
          mvn -version
      - name: Cache Maven dependencies
        run: |
          mkdir -p ~/.m2 && cp -r ./.m2 ~/.m2 || echo "No Maven cache to restore."
      - name: Run tests
        run: |
          mvn clean verify
      - name: Generate coverage report
        run: |
          mvn jacoco:report
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco


  push_to_mirror:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
